# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6419341dffec01ba100196285783e9ce38b8200835d960a17f91252363317b3644d1d53ec4ca9f36049703a7b0398d0c72742781b20ed23377db1497029db8f

test:
  secret_key_base: 4678a6614b44632663e3ebf345501e31b401732c89b94f920ab223d6296d2f102aa05269157c3989afbe87ec265a690f32ab02a872f44ab90d9d55510a6c87a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
