user = User.create(username: 'admin', password: 'password', password_confirmation: 'password', email: 'admin@example.com')

Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
Spot.create(name: 'asdfa', description: 'asdfasdfasd', user_id: user.id)
